import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import { cn } from "@/lib/utils"
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Harmoney Music From",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider>
        <html lang="en" className="dark">
            <body className={inter.className}>
            <header>
              <Image
              hidden
              src='/favicon.ico'
              alt="music-icon"
              width={50}
              height={50}
              />
            </header>
              <div className="w-full relative flex flex-2 items-center justify-center">
                <Navbar/>
              </div>
      
              {children}
            </body>
          </html>
      </ClerkProvider>
  );
}
